### ISSUE TITLE
Not writing coins

### ISSUE THREAD

**Issue by Heinrichxiao** [Heinrich-XIAO/Heinrich-XIAO.github.io#1]
The coins in the math directory isn't working.

**Comment by Heinrich-XIAO** [comment]
I think it has to do with the local storage.

**Comment by Heinrich-XIAO** [comment]
https://github.com/Heinrich-XIAO/Heinrich-XIAO.github.io/blob/fcd891acbabd8f77618a6643bd0c03e8714746d1/math/app.js#L56

**Comment by Heinrichxiao** [comment]
I'm going to merge the branches together.

**Comment by Heinrich-XIAO** [comment]
I fixed the bug

**Comment by Heinrichxiao** [comment]
Super!!
